server:
  port: 8090
spring:
  application.name: loa-app
  boot.admin.client.url: http://localhost:9090
logging:
  file: 
    name: target/logs/client.log
  level:
    root: WARN
    org.springframework.web: INFO    
    org.linkedopenactors: TRACE
    org.linkedopenactors.code.kvmadapter.initial: TRACE
#    org.linkedopenactors.code.kvmadapter: INFO
#    de.naturzukunft.rdf4j.loarepository: INFO
#    de.naturzukunft.rdf4j.loarepository.BaseObjectRepository: DEBUG
    de.naturzukunft: DEBUG
    org.eclipse.rdf4j: INFO    
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    logfile:
      enabled: true
      external-file: target/logs/client.log      
springdoc:
    swagger-ui:
        oauth:
            token-url: http://localhost:8080/auth/realms/LOA/protocol/openid-connect/token
            clientId: loa
            clientSecret: loa
    writer-with-default-pretty-printer: true
app:
  rdfRepositoryHome: target/repoManager
  baseNamespace: http://localhost:8090/
  baseSubjectSystem: https://loa.test.opensourceecology.de/system/
  searchForChangesInTheLastMinutes: 180
  kvmUrl: https://api.ofdb.io/v0/
  baseSubjectKvm: http://linkedopenactors.org/kvm/
  rdf4jServer: https://rdf.dev.osalliance.com/rdf4j-server/
  osmUrl: https://overpass.kumi.systems/api/interpreter/?data=[out:json][timeout:180]
  osmFilter: '[~"^(organic|diet:vegan|diet:vegetarian|fair_trade|regional|second_hand|charity|ngo|identity)$"~"^([^nN].*|[nN][^oO].*|[nN][oO]. )$"];out qt;'
  repositoryIdOsm: osm_loa
  repositoryIdKvm: kvm_loa  
  repositoryIdWeChange: weChange_loa