app:
  rdfRepositoryHome: /mnt/spring
  baseNamespace: https://loa.test.opensourceecology.de/
logging:
  file: 
    name: /mnt/spring/logs/client.log
management:
  endpoint:
    logfile.external-file: /mnt/spring/logs/client.log
spring:
  boot.admin.client.url: https://loa-spring-boot-admin.test.opensourceecology.de
  